kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node:12.19.1-alpine
    commands:
      - npm install
  - name: lint
    image: node:12.19.1-alpine
    commands:
      - npm run lint
  - name: build
    image: node:12.19.1-alpine
    commands:
      - npm run build
  - name: storybook
    image: node:12.19.1-alpine
    commands:
      - npm run build-storybook
